/*
 * AC1 - Linguagem de Programacao - ADS
 * Exemplo escrito por Robson Martins
 */
package br.facens;

import javax.swing.JOptionPane;

public class Batalha extends javax.swing.JFrame {

    /**
     * Creates new form Batalha
     */
    public Batalha() {
        initComponents();
        String[] tipos = { "agua", "fogo", "terra", "ar", "outro" };
        cbTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(tipos));
        cbTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(tipos));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNome1 = new javax.swing.JTextField();
        btnImprimir1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbTipo1 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtNome2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        cbTipo2 = new javax.swing.JComboBox<>();
        btnImprimir2 = new javax.swing.JButton();
        btnBatalhar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalha Pokemón - by Prof. Robson Martins");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Pokemón 1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));
        jPanel1.add(txtNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 104, -1));

        btnImprimir1.setText("Imprimir");
        btnImprimir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimir1MouseClicked(evt);
            }
        });
        jPanel1.add(btnImprimir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, -1));

        jLabel3.setText("Tipo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, -1, -1));

        jLabel2.setText("Nome:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        cbTipo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 104, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Pokemón 2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));
        jPanel1.add(txtNome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 104, -1));

        jLabel6.setText("Tipo:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, -1));

        cbTipo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(cbTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 130, 104, -1));

        btnImprimir2.setText("Imprimir");
        btnImprimir2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnImprimir2MouseClicked(evt);
            }
        });
        jPanel1.add(btnImprimir2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        btnBatalhar.setText("Batalhar!");
        btnBatalhar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalharMouseClicked(evt);
            }
        });
        jPanel1.add(btnBatalhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, -1, -1));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/facens/poke.png"))); // NOI18N
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimir1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimir1MouseClicked
        if (null == txtNome1.getText() || txtNome1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Digite um nome válido para o Pokemón 1.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Pokemon p1 = new Pokemon(txtNome1.getText(), String.valueOf(cbTipo1.getSelectedItem()));
        p1.imprimir();
    }//GEN-LAST:event_btnImprimir1MouseClicked

    private void btnImprimir2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnImprimir2MouseClicked
        if (null == txtNome2.getText() || txtNome2.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Digite um nome válido para o Pokemón 2.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Pokemon p2 = new Pokemon(txtNome2.getText(), String.valueOf(cbTipo2.getSelectedItem()));
        p2.imprimir();
    }//GEN-LAST:event_btnImprimir2MouseClicked

    private void btnBatalharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalharMouseClicked
        if (null == txtNome1.getText() || txtNome1.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Digite um nome válido para o Pokemón 1.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (null == txtNome2.getText() || txtNome2.getText().isBlank()) {
            JOptionPane.showMessageDialog(this, "Digite um nome válido para o Pokemón 2.", "Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Pokemon p1 = new Pokemon(txtNome1.getText(), String.valueOf(cbTipo1.getSelectedItem()));
        Pokemon p2 = new Pokemon(txtNome2.getText(), String.valueOf(cbTipo2.getSelectedItem()));
        if (p1.getVida() > p2.getVida()) {
            JOptionPane.showMessageDialog(this, "O Pokemón \"" + p1.getNome() + "\" venceu!", "Vencedor", JOptionPane.INFORMATION_MESSAGE);
        } else if (p2.getVida() > p1.getVida()) {
            JOptionPane.showMessageDialog(this, "O Pokemón \"" + p2.getNome() + "\" venceu!", "Vencedor", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Houve um empate entre o Pokemón \"" + p1.getNome() + "\" e o Pokemón \"" + p2.getNome() + "\"!",
                    "Vencedor", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnBatalharMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Batalha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Batalha b = new Batalha();
                b.setLocationRelativeTo(null);
                b.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatalhar;
    private javax.swing.JButton btnImprimir1;
    private javax.swing.JButton btnImprimir2;
    private javax.swing.JComboBox<String> cbTipo1;
    private javax.swing.JComboBox<String> cbTipo2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNome1;
    private javax.swing.JTextField txtNome2;
    // End of variables declaration//GEN-END:variables
}
